# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
parameters:
    system_domain_discriminator: berform
    system_no_reply_email: 'no-reply@berform.com'
    resource_provider_domain: '%env(RESOURCE_PROVIDER_DOMAIN)%'
    platform_main_domain: '%env(PLATFORM_MAIN_DOMAIN)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook_secret_key: '%env(STRIPE_WEBHOOK_SECRET_KEY)%'