framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
jms_i18n_routing:
    default_locale: bg
    locales: [en, bg]
    strategy: prefix_except_default