# SYMFONy 4 DELETE
#framework:
#    default_locale: en
#    translator:
#        default_path: '%kernel.project_dir%/translations'
#        fallbacks:
#            - en
framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
jms_i18n_routing:
    default_locale: en
    locales: [bg, en]
    strategy: prefix
