twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        resource_provider_domain: '%resource_provider_domain%'
        stripe_public_key: '%env(resolve:STRIPE_PUBLIC_KEY)%'
        stripe_default_uk_price_yearly: '%env(resolve:STRIPE_DEFAULT_UK_PRICE_YEARLY)%'