version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: symfony-docker
    tty: true
    ports:
      - 8080:80
    volumes:      
      - .:/var/www
