index:
    path: /
    controller: App\Controller\LandingSiteController::home
admin:
    path: /u
    controller: App\Controller\Admin\SiteController::list

user_admin_site_build:
    path: /u/site/build/{id}
    controller: App\Controller\Admin\BuilderController::buildSite
user_admin_site_list:
    path: /u/site/list
    controller: App\Controller\Admin\SiteController::list
user_admin_site_create:
    path: /u/site/create
    controller: App\Controller\Admin\SiteController::create
user_admin_site_edit:
    path: /u/site/edit/{id}
    controller: App\Controller\Admin\SiteController::edit
user_admin_site_delete:
    path: /u/site/delete/{id}
    controller: App\Controller\Admin\SiteController::delete

# pages
admin_page_edit:
    path: /u/page/{id}
    controller: App\Controller\Admin\PageController::edit

# uploads
user_admin_site_upload_handler:
    path: /u/site/{page}/upload
    controller: App\Controller\Admin\UploadController::upload
