index:
    path: /
    host: sitemax.kik
    controller: App\Controller\LandingSiteController::home

admin:
    path: /u
    controller: App\Controller\Admin\DashboardController::dashboard

user_admin_site_build:
    path: /u/site/build/{id}
    controller: App\Controller\Admin\BuilderController::buildSite
# sign up
app_login:
    path: /login
    controller: App\Controller\SignupController::login

app_registration:
    path: /register
    controller: App\Controller\SignupController::register

app_signup_choose_template:
    path: /sign-up/choose-template/{id}
    controller: App\Controller\SignupController::chooseTemplate

app_signup_setup_account:
    path: /sign-up/setup-account
    controller: App\Controller\SignupController::setupAccount

# sites
user_admin_site_list:
    path: /u/site/list
    controller: App\Controller\Admin\SiteController::list
user_admin_site_create:
    path: /u/site/create
    controller: App\Controller\Admin\SiteController::create
user_admin_site_edit:
    path: /u/site/edit/{id}
    controller: App\Controller\Admin\SiteController::edit
user_admin_site_delete:
    path: /u/site/delete/{id}
    controller: App\Controller\Admin\SiteController::delete

# domains
user_admin_domain_create:
    path: /u/domain/create
    controller: App\Controller\Admin\DomainController::create
user_admin_domain_edit:
    path: /u/domain/edit/{id}
    controller: App\Controller\Admin\DomainController::edit
user_admin_domain_delete:
    path: /u/domain/delete/{id}
    controller: App\Controller\Admin\DomainController::delete

user_admin_domain_list:
    path: /u/domain/list
    controller: App\Controller\Admin\DomainController::list

# pages
user_admin_page_create:
    path: /u/page/create/{site}
    controller: App\Controller\Admin\PageController::create
user_admin_page_edit:
    path: /u/page/{id}
    controller: App\Controller\Admin\PageController::edit

# posts
user_admin_post_create:
    path: /u/post/create/{site}
    controller: App\Controller\Admin\PostController::create
user_admin_post_list:
    path: /u/blog/post/list/{site}
    controller: App\Controller\Admin\PostController::list
user_admin_post_edit:
    path: /u/post/{site}/{id}
    controller: App\Controller\Admin\PostController::edit

# uploads
admin_site_upload_handler:
    path: /u/site/{site}/upload
    controller: App\Controller\Admin\UploadController::upload

admin_site_upload_delete:
    path: /u/site/upload/{id}
    controller: App\Controller\Admin\UploadController::deleteFile

# profile
admin_profile_edit:
    path: /u/profile/edit
    controller: App\Controller\Admin\ProfileController::edit

## billing
#admin_billing:
#    path: /u/billing/payment/list
#    controller: App\Controller\admin\BillingController::listPayments
admin_billing_cart_add:
    path: /u/billing/cart/add/{product}/{subscription}
    controller: App\Controller\Admin\Billing\CartController::addProduct

admin_billing_cart_view:
    path: /u/billing/cart/view
    controller: App\Controller\Admin\Billing\CartController::view

admin_profile_change_password:
    path: /u/profile/change_password
    controller: App\Controller\Admin\ProfileController::changePassword


app_logout:
    path: /logout

# user site
user_site_contact:
    path: /contact/send_message
    controller: App\Controller\ContactController::sendMessage

# user site
user_site_blog:
    path: /blog
    controller: App\Controller\BlogController::list

user_site_blog_view_post:
    path: /blog/{slug}
    controller: App\Controller\BlogController::view

user_site_view_page_home:
    path: /
    controller: App\Controller\UserSiteController::renderPage

user_site_view_page:
    path: /{slug}
    controller: App\Controller\UserSiteController::renderPage
