index:
    path: /
    host: sitemax.kik
    controller: App\Controller\LandingSiteController::home

admin:
    path: /u
    controller: App\Controller\Admin\DashboardController::dashboard

user_admin_site_build:
    path: /u/site/build/{id}
    controller: App\Controller\Admin\BuilderController::buildSite
# security
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_registration:
    path: /register
    controller: App\Controller\SecurityController::register



# sites
user_admin_site_list:
    path: /u/site/list
    controller: App\Controller\Admin\SiteController::list
user_admin_site_create:
    path: /u/site/create
    controller: App\Controller\Admin\SiteController::create
user_admin_site_edit:
    path: /u/site/edit/{id}
    controller: App\Controller\Admin\SiteController::edit
user_admin_site_delete:
    path: /u/site/delete/{id}
    controller: App\Controller\Admin\SiteController::delete

# domains
user_admin_domain_create:
    path: /u/domain/create
    controller: App\Controller\Admin\DomainController::create
user_admin_domain_edit:
    path: /u/domain/edit/{id}
    controller: App\Controller\Admin\DomainController::edit
user_admin_domain_delete:
    path: /u/domain/delete/{id}
    controller: App\Controller\Admin\DomainController::delete

# pages
user_admin_page_create:
    path: /u/page/create/{site}
    controller: App\Controller\Admin\PageController::create
user_admin_page_edit:
    path: /u/page/{id}
    controller: App\Controller\Admin\PageController::edit

# posts
user_admin_post_create:
    path: /u/post/create/{site}
    controller: App\Controller\Admin\PostController::create
user_admin_post_edit:
    path: /u/post/{site}/{id}
    controller: App\Controller\Admin\PostController::edit

# uploads
admin_site_upload_handler:
    path: /u/site/{site}/upload
    controller: App\Controller\Admin\UploadController::upload

admin_site_upload_delete:
    path: /u/site/upload/{id}
    controller: App\Controller\Admin\UploadController::deleteFile

app_logout:
    path: /logout

# user site
user_site_contact:
    path: /contact/send_message
    controller: App\Controller\ContactController::sendMessage

user_site_render_page:
    path: /{slug}
    controller: App\Controller\UserSiteController::renderPage
    defaults:
        slug: home